[v1]
"bacon 2.14.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bacon"]
"cargo-expand 1.0.74 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-show-asm 0.2.23 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-asm"]
"irust 1.71.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["irust"]
"ripgrep 14.0.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
